"""The Part 3 write-up, generated from a `ComparisonResult`.

Spec Part 3 asks which populations differ significantly, with statistics good
enough to convince a colleague. On the delivered data the answer is that none
do, and a null result is worth reading only when it is bounded. "We found
nothing" is not a finding. "No population differs, and shifts larger than this
are ruled out at 95% confidence" is one, because it tells the reader what the
study could and could not have seen.

So the document leads with the bound rather than the p-values, and it states
the cohort, the group sizes in both samples and subjects, and the independence
decision that made those group sizes what they are.

Every number is read from the result rather than transcribed, and the
conclusion branches on the data. A document that hardcoded "nothing is
significant" would keep saying so after the data changed, which is the failure
mode a generated report exists to prevent.

Sentences are written one per line. Diffs then show which sentence changed
rather than which paragraph reflowed.
"""

from __future__ import annotations

from collections.abc import Callable, Sequence

from cellcount.cohort import Cohort
from cellcount.comparison import (
    ComparisonResult,
    PopulationComparison,
    group_label,
    simultaneous_alpha,
    yekutieli_q_values,
)

_NO_SAMPLES = "No samples matched this cohort, so there is nothing to compare."

_TITLE = "# Part 3: does baseline immune composition predict response to miraclib?"

_PROVENANCE = (
    "Generated by `make pipeline` from the database it had just loaded.\n"
    "Every number below is read from the comparison that produced it, "
    "not transcribed."
)


def _fmt(value: float | None, digits: int = 3) -> str:
    return "" if value is None else f"{value:.{digits}f}"


def _signed(value: float | None, digits: int = 2) -> str:
    return "" if value is None else f"{value:+.{digits}f}"


def _join(values: Sequence[object]) -> str:
    """Render a list the way prose does: "a", "a and b", "a, b and c"."""
    items = [str(value) for value in values]
    if len(items) <= 1:
        return "".join(items)
    return f"{', '.join(items[:-1])} and {items[-1]}"


def _describe_cohort(cohort: Cohort) -> str:
    parts: list[str] = []
    if cohort.condition:
        parts.append(f"`condition = {cohort.condition}`")
    if cohort.treatment:
        parts.append(f"`treatment = {cohort.treatment}`")
    if cohort.sex:
        parts.append(f"`sex = {cohort.sex}`")
    if cohort.response:
        parts.append(f"`response = {cohort.response}`")
    if cohort.sample_type:
        parts.append(f"`sample_type = {cohort.sample_type}`")
    if cohort.timepoints:
        if len(cohort.timepoints) == 1:
            parts.append(f"`time_from_treatment_start = {cohort.timepoints[0]}`")
        else:
            listed = ", ".join(str(t) for t in cohort.timepoints)
            parts.append(f"`time_from_treatment_start` in ({listed})")
    return _join(parts) if parts else "every sample in the database"


Interval = Callable[[PopulationComparison], tuple[float, float] | None]


def _marginal_ci(comparison: PopulationComparison) -> tuple[float, float] | None:
    """The interval covering this population alone, at alpha."""
    return comparison.shift_ci


def _simultaneous_ci(comparison: PopulationComparison) -> tuple[float, float] | None:
    """The interval from the family that covers every population at alpha."""
    return comparison.simultaneous_ci


def _half_width(interval: tuple[float, float] | None) -> float | None:
    """How far an interval reaches from zero, in either direction.

    This is what the data exclude: a true shift beyond it is outside the
    interval on one side or the other. Which side that is varies by population,
    so both endpoints are measured rather than only the lower one.
    """
    if interval is None:
        return None
    low, high = interval
    return max(abs(low), abs(high))


def _widest_bound(
    result: ComparisonResult, interval: Interval
) -> tuple[str, float] | None:
    """The population whose interval reaches furthest, and how far.

    Populations are visited in the order the result reports them, which is
    sorted, so a tie resolves the same way on every run.
    """
    bounded = [
        (comparison.population, half_width)
        for comparison in result.populations
        if (half_width := _half_width(interval(comparison))) is not None
    ]
    if not bounded:
        return None
    return max(bounded, key=lambda pair: pair[1])


def _largest_shift(result: ComparisonResult) -> tuple[str, float] | None:
    """The biggest estimated shift in either direction, and where it is.

    Ranked on magnitude, not on signed value: the largest shift in this data is
    positive at baseline and negative at both later timepoints, and a document
    that reported the largest positive one would misdescribe two of the three.
    """
    shifts = [
        (comparison.population, comparison.shift)
        for comparison in result.populations
        if comparison.shift is not None
    ]
    if not shifts:
        return None
    return max(shifts, key=lambda pair: abs(pair[1]))


def _interval_excludes_zero(result: ComparisonResult) -> list[str]:
    """Populations whose interval misses zero although their q-value clears alpha.

    The two answer different questions, so they disagree by design: the
    interval covers one population at `alpha`, while the q-value is adjusted
    across every tested population. It happens in the delivered data, at t = 7
    and t = 14, and a reader who took the interval as the verdict would report
    a difference the correction does not support. Saying so is cheaper than
    fielding the question later.
    """
    return [
        comparison.population
        for comparison in result.populations
        if comparison.shift_ci is not None
        and comparison.q_value is not None
        and comparison.q_value > result.alpha
        and (comparison.shift_ci[0] > 0.0 or comparison.shift_ci[1] < 0.0)
    ]


def _disagreement_note(entries: Sequence[tuple[Sequence[str], str]]) -> list[str]:
    """Name every such population once, then explain the disagreement once.

    Repeating the explanation per timepoint would bury the list it qualifies.
    """
    phrases = [
        _join([f"`{name}`" for name in names]) + (f" {where}" if where else "")
        for names, where in entries
        if names
    ]
    if not phrases:
        return []
    total = sum(len(names) for names, _ in entries)
    return [
        f"Note that {_join(phrases)} {'have' if total > 1 else 'has'} an "
        "interval that excludes zero while the q-value does not clear the "
        "threshold.",
        "That is not a contradiction: the interval covers one population at "
        "alpha, the q-value is adjusted across every population tested, and "
        "the q-value is what governs the conclusion.",
    ]


def _significant(result: ComparisonResult) -> list[PopulationComparison]:
    return [
        comparison
        for comparison in result.populations
        if comparison.q_value is not None and comparison.q_value <= result.alpha
    ]


def _confidence(result: ComparisonResult) -> str:
    return f"{(1.0 - result.alpha) * 100:g}%"


def _per_interval_confidence(result: ComparisonResult) -> str:
    """The level each interval carries once the family is corrected to `alpha`."""
    adjusted = simultaneous_alpha(result.alpha, result.n_tested)
    return f"{(1.0 - adjusted) * 100:g}%"


def _joint_floor(result: ComparisonResult) -> str:
    """The joint coverage a family of marginal intervals still guarantees.

    The union bound, so it is a floor rather than the true coverage, which
    depends on a dependence structure this data does not hand us.
    """
    return f"{max(0.0, 1.0 - result.n_tested * result.alpha) * 100:g}%"


def _headline(result: ComparisonResult) -> list[str]:
    lines = ["## Answer", ""]
    significant = _significant(result)
    confidence = _confidence(result)

    if significant:
        named = _join(
            [
                f"`{comparison.population}` (q = {_fmt(comparison.q_value)}, "
                f"shift {_signed(comparison.shift)} percentage points)"
                for comparison in significant
            ]
        )
        lines.append(
            f"{len(significant)} of {result.n_tested} tested populations differ "
            f"between the two arms at q <= {result.alpha:g}: {named}."
        )
        remaining = len(result.populations) - len(significant)
        if remaining:
            lines.append(
                f"The remaining {remaining} did not reach the threshold; "
                f"the intervals below say how large a difference they still allow."
            )
    else:
        lines.append("No population differs significantly between the two arms.")
        bound = _widest_bound(result, _simultaneous_ci)
        if bound is not None:
            population, half_width = bound
            lines.append(
                f"The comparison is bounded rather than merely inconclusive: "
                f"at {confidence} simultaneous confidence over all "
                f"{result.n_tested} populations tested, it rules out any shift "
                f"larger than {half_width:.2f} percentage points, the widest "
                f"interval being `{population}`'s."
            )
        largest = _largest_shift(result)
        if largest is not None:
            population, shift = largest
            lines.append(
                f"`{population}` carries the largest estimated shift, "
                f"{shift:+.2f} percentage points."
            )
    lines.append("")
    return lines


def _cohort_section(result: ComparisonResult) -> list[str]:
    first, second = result.groups
    lines = [
        "## Cohort",
        "",
        f"{_describe_cohort(result.cohort)}.",
        "",
        "| arm | samples | subjects |",
        "| --- | ---: | ---: |",
    ]
    for group in (first, second):
        lines.append(
            f"| {group_label(group)} (`{group}`) | "
            f"{result.n_samples[group]:,} | {result.n_subjects[group]:,} |"
        )
    lines.append("")
    described = "; ".join(
        f"{group_label(group)}, {result.n_samples[group]:,} samples from "
        f"{result.n_subjects[group]:,} subjects"
        for group in (first, second)
    )
    lines.append(f"That is {described}.")

    if result.repeated_measures:
        lines.append(
            "At least one subject contributes more than one sample here, so "
            "these are repeated measures and the observations are not "
            "independent."
        )
        lines.append(
            "Mann-Whitney assumes independence, so the p-values below are "
            "anticonservative and should be read as a screen rather than as "
            "evidence."
        )
    else:
        lines.append(
            "Each subject contributes exactly one sample, so the observations "
            "are independent and the test's assumption holds."
        )
    lines.append("")
    return lines


def _why_baseline(result: ComparisonResult) -> list[str]:
    first, second = result.groups
    return [
        "### Why baseline, and not every timepoint pooled",
        "",
        "Subjects in this trial are sampled repeatedly, so pooling timepoints "
        "would count several correlated samples from one subject as several "
        "independent observations.",
        "That inflates the apparent sample size without adding a single "
        "subject, and a rank test fed pseudo-replicates returns p-values that "
        "are too small.",
        f"Restricting to baseline costs little: the arms still hold "
        f"{result.n_subjects[first]:,} and {result.n_subjects[second]:,} "
        f"subjects.",
        "",
        "Baseline also answers the question that was asked.",
        "A difference measured before treatment could be used to choose "
        "treatment; a difference that appears afterwards may be a consequence "
        "of responding rather than a predictor of it.",
        "",
    ]


def _method(result: ComparisonResult) -> list[str]:
    first, _ = result.groups
    return [
        "## Method",
        "",
        "Mann-Whitney U, two-sided, on the relative frequencies from the "
        "Part 2 summary table.",
        f"Benjamini-Hochberg across the {result.n_tested} populations that "
        f"could be tested, at alpha = {result.alpha:g}.",
        "Shift is the Hodges-Lehmann estimate, the median of every pairwise "
        f"difference, in percentage points and oriented so that a positive "
        f"value means the {group_label(first)} arm is higher.",
        f"Its interval inverts the same test at {_confidence(result)} for that "
        "population alone and is not adjusted for multiplicity, so "
        "significance is judged by the q-value and magnitude by the interval.",
        f"Every interval in the results table is marginal at that level; the "
        f"headline bound instead uses the Bonferroni-widened family, each "
        f"interval taken at alpha / {result.n_tested} so that all "
        f"{result.n_tested} hold together at {_confidence(result)}.",
        "Effect size is P(x > y) + 0.5 P(x = y) with x drawn from the "
        f"{group_label(first)} arm, so 0.5 means no separation at all.",
        "",
    ]


def _results_table(result: ComparisonResult) -> list[str]:
    first, second = result.groups
    lines = [
        "## Results",
        "",
        f"| population | median, {group_label(first)} | "
        f"median, {group_label(second)} | shift (pp) | "
        f"{_confidence(result)} CI (pp) | p | q | effect size |",
        "| --- | ---: | ---: | ---: | --- | ---: | ---: | ---: |",
    ]
    untested: list[str] = []
    for comparison in result.populations:
        if comparison.q_value is None:
            untested.append(comparison.population)
            lines.append(
                f"| `{comparison.population}` | "
                f"{_fmt(comparison.median[first])} | "
                f"{_fmt(comparison.median[second])} | not tested |  |  |  |  |"
            )
            continue
        low, high = comparison.shift_ci if comparison.shift_ci else (None, None)
        lines.append(
            f"| `{comparison.population}` | "
            f"{_fmt(comparison.median[first])} | "
            f"{_fmt(comparison.median[second])} | "
            f"{_signed(comparison.shift)} | "
            f"[{_signed(low)}, {_signed(high)}] | "
            f"{_fmt(comparison.p_value)} | "
            f"{_fmt(comparison.q_value)} | "
            f"{_fmt(comparison.effect_size)} |"
        )
    lines.append("")
    lines.append("Medians are percentages of each sample's own total count.")
    if untested:
        lines.append(
            f"{_join([f'`{name}`' for name in untested])} could not be tested: "
            "either one arm had too few samples, or every observation was "
            "identical, which leaves a rank test nothing to rank."
        )
        lines.append(
            "An untested population is kept out of the correction rather than "
            "entered at p = 1, which is why the family size above may be "
            "smaller than the number of rows."
        )
    lines += _disagreement_note([(_interval_excludes_zero(result), "")])
    lines.append("")
    return lines


def _bound_section(result: ComparisonResult) -> list[str]:
    marginal = _widest_bound(result, _marginal_ci)
    if marginal is None:
        return []
    population, half_width = marginal
    confidence = _confidence(result)
    lines = [
        "## What this sample size rules out",
        "",
        "A p-value above the threshold says a difference was not detected.",
        "It does not say there is none, and on its own it is not a result "
        "anyone can act on.",
        "The intervals are what bound the claim.",
        "",
        f"Each interval in the results table is marginal: it covers its own "
        f"population at {confidence} and says nothing about the others.",
        f"The widest of them reaches {half_width:.2f} percentage points, in "
        f"`{population}`.",
    ]

    # The headline quantifies over populations, so it needs the family to hold
    # jointly. Marginal intervals do not give it that, and the gap is large
    # enough to matter: five at 95% guarantee only 75% together.
    joint = _widest_bound(result, _simultaneous_ci)
    if joint is not None and result.n_tested > 1:
        joint_population, joint_half_width = joint
        lines += [
            f"Reading all {result.n_tested} of them at once is a different "
            f"claim, though, and one they do not support: {result.n_tested} "
            f"marginal {confidence} intervals guarantee only "
            f"{_joint_floor(result)} joint coverage.",
            f"Recomputing each at alpha / {result.n_tested}, which is "
            f"{_per_interval_confidence(result)} apiece, restores "
            f"{confidence} for the set, and the widest then reaches "
            f"{joint_half_width:.2f} percentage points, in "
            f"`{joint_population}`.",
            f"At {confidence} simultaneous confidence, then, the data exclude "
            f"any true shift larger than {joint_half_width:.2f} percentage "
            f"points in every population at once; the marginal bounds in the "
            f"table are tighter because each covers only one population.",
        ]
        population, half_width = joint_population, joint_half_width
    else:
        lines.append(
            f"At {confidence} confidence, then, the data exclude any true "
            f"shift larger than {half_width:.2f} percentage points."
        )

    widest = next(
        comparison
        for comparison in result.populations
        if comparison.population == population
    )
    typical = sum(widest.median.values()) / len(widest.median)
    if typical > 0:
        lines.append(
            f"For scale, `{population}` sits at roughly {typical:.2f}% of the "
            f"cells in a sample, so that bound is about "
            f"{100.0 * half_width / typical:.1f}% of the population's own "
            "frequency."
        )
        lines.append(
            "A cohort this size can therefore exclude a large relative "
            "difference and not a small one."
        )
    lines.append("")
    return lines


def _timepoint_section(
    by_timepoint: Sequence[tuple[int, ComparisonResult]],
    skipped: Sequence[int],
) -> list[str]:
    if not by_timepoint and not skipped:
        return []

    lines = [
        "## Secondary view: each timepoint on its own",
        "",
        "Benjamini-Hochberg is applied within each timepoint, not across "
        "them, so a q-value below is corrected over the same family size as "
        "the headline and not over three times it.",
        "The timepoints are still not independent of one another, since the "
        "same subjects appear in all of them, so this is a consistency check "
        "rather than three separate studies.",
        "",
    ]

    if by_timepoint:
        # A timepoint that matched nothing has no group names, so the header
        # comes from the first entry that does have them.
        named = next(
            (result for _, result in by_timepoint if len(result.groups) == 2), None
        )
        first, second = named.groups if named else ("", "")
        lines += [
            f"| timepoint | {group_label(first)} (samples) | "
            f"{group_label(second)} (samples) | "
            "populations tested | smallest q | widest marginal bound (pp) |",
            "| --- | ---: | ---: | ---: | ---: | ---: |",
        ]
        for timepoint, result in by_timepoint:
            q_values = [
                comparison.q_value
                for comparison in result.populations
                if comparison.q_value is not None
            ]
            bound = _widest_bound(result, _marginal_ci)
            lines.append(
                f"| t = {timepoint} | "
                f"{result.n_samples.get(first, 0):,} | "
                f"{result.n_samples.get(second, 0):,} | "
                f"{result.n_tested} | "
                f"{_fmt(min(q_values)) if q_values else 'n/a'} | "
                f"{f'{bound[1]:.2f}' if bound else 'n/a'} |"
            )
        lines.append("")

        significant = {
            timepoint: [c.population for c in _significant(result)]
            for timepoint, result in by_timepoint
        }
        flagged = {t: names for t, names in significant.items() if names}
        if flagged:
            lines.append(
                "Populations reaching the threshold: "
                + _join(
                    [
                        f"t = {timepoint} ({_join(names)})"
                        for timepoint, names in sorted(flagged.items())
                    ]
                )
                + "."
            )
        else:
            lines.append(
                "Nothing reaches the threshold at any timepoint, which is the "
                "same conclusion the headline reaches and not an independent "
                "confirmation of it."
            )

        lines += _disagreement_note(
            [
                (_interval_excludes_zero(result), f"at t = {timepoint}")
                for timepoint, result in by_timepoint
            ]
        )
        lines.append("")

    if skipped:
        lines.append(
            f"Timepoint{'s' if len(skipped) > 1 else ''} "
            f"{_join(list(skipped))} did not yield two response groups and "
            f"{'were' if len(skipped) > 1 else 'was'} not compared."
        )
        lines.append("")

    return lines


def _yekutieli_check(
    result: ComparisonResult,
    by_timepoint: Sequence[tuple[int, ComparisonResult]],
) -> list[str]:
    """Re-run every correction the document reports under Benjamini-Yekutieli.

    The paragraph above says the dependence condition Benjamini-Hochberg needs
    is not established here. That is a reason to check, not a reason to stop,
    and the check is cheap: Benjamini-Yekutieli holds under arbitrary
    dependence. Reported as numbers rather than as reassurance, and branching
    on them, so the claim can be withdrawn by the data that produced it.
    """
    headline = yekutieli_q_values(result)
    if not headline:
        return []

    alpha = result.alpha
    smallest_bh = min(
        comparison.q_value
        for comparison in result.populations
        if comparison.q_value is not None
    )
    lines = [
        "So the same p-values were re-corrected under Benjamini-Yekutieli, "
        "which holds under arbitrary dependence, as a check on that assumption "
        "rather than as a replacement for the headline correction.",
        f"In the headline family the smallest q-value moves from "
        f"{_fmt(smallest_bh)} to {_fmt(min(headline.values()))}.",
    ]

    families = [(result, headline)]
    per_timepoint: list[tuple[int, float]] = []
    for timepoint, timed in by_timepoint:
        adjusted = yekutieli_q_values(timed)
        if adjusted:
            families.append((timed, adjusted))
            per_timepoint.append((timepoint, min(adjusted.values())))
    if per_timepoint:
        when, smallest = min(per_timepoint, key=lambda pair: pair[1])
        lines.append(
            f"Across the per-timepoint families the smallest becomes "
            f"{_fmt(smallest)}, at t = {when}."
        )

    hochberg = sorted(
        {
            comparison.population
            for family, _ in families
            for comparison in _significant(family)
        }
    )
    yekutieli = sorted(
        {
            name
            for family, adjusted in families
            for name, q_value in adjusted.items()
            if q_value <= family.alpha
        }
    )
    lost = [name for name in hochberg if name not in yekutieli]
    if not hochberg and not yekutieli:
        lines.append(
            f"No q-value reaches alpha = {alpha:g} under either correction, so "
            "the conclusion above does not rest on the dependence assumption."
        )
    elif lost:
        lines.append(
            f"{_join([f'`{name}`' for name in lost])} clears alpha = "
            f"{alpha:g} under Benjamini-Hochberg and not under "
            "Benjamini-Yekutieli, so that much of the conclusion does rest on "
            "the dependence assumption."
        )
    else:
        lines.append(
            f"Every population that clears alpha = {alpha:g} under "
            "Benjamini-Hochberg clears it under Benjamini-Yekutieli too, so "
            "the conclusion above does not rest on the dependence assumption."
        )
    return lines


def _caveats(
    result: ComparisonResult,
    by_timepoint: Sequence[tuple[int, ComparisonResult]] = (),
) -> list[str]:
    return [
        "## Caveats worth stating",
        "",
        "The frequencies sum to 100 by construction, so they are not "
        "independent measurements: a shift in one implies compensating shifts "
        "in the others.",
        "Closure constrains the covariance structure, since each part's "
        "covariances with the rest must sum to minus its own variance, so the "
        "parts cannot all be positively related to one another.",
        "That does not make every pair negatively correlated, but it does mean "
        "the positive regression dependence Benjamini-Hochberg is proved under "
        "is not something this design establishes.",
        *_yekutieli_check(result, by_timepoint),
        "",
        "Mann-Whitney tests stochastic dominance, and is a test of medians "
        "only when the two distributions have the same shape.",
        "The medians are reported anyway because they are what a reader wants, "
        "and the shift, which is what the test estimates, is reported beside "
        "them.",
        "",
        "This says nothing about absolute counts, about populations outside "
        "this panel of five, or about a subgroup the cohort does not isolate.",
        "It is a statement about relative frequencies in the samples that were "
        "measured.",
        "",
    ]


def findings_markdown(
    baseline: ComparisonResult,
    by_timepoint: Sequence[tuple[int, ComparisonResult]] = (),
    *,
    skipped_timepoints: Sequence[int] = (),
) -> str:
    """Render the Part 3 write-up as markdown.

    `baseline` is the headline comparison; `by_timepoint` is the secondary
    per-timepoint panel, each entry already corrected within itself.
    `skipped_timepoints` names timepoints that could not be compared, so the
    document says why one is missing rather than leaving a gap.
    """
    lines = [_TITLE, "", _PROVENANCE, ""]

    if not baseline.populations or len(baseline.groups) != 2:
        lines += [
            "## Answer",
            "",
            _NO_SAMPLES,
            f"The cohort was {_describe_cohort(baseline.cohort)}.",
            "",
        ]
        return "\n".join(lines) + "\n"

    lines += _headline(baseline)
    lines += _cohort_section(baseline)
    lines += _why_baseline(baseline)
    lines += _method(baseline)
    lines += _results_table(baseline)
    lines += _bound_section(baseline)
    lines += _timepoint_section(by_timepoint, skipped_timepoints)
    lines += _caveats(baseline, by_timepoint)
    return "\n".join(lines).rstrip("\n") + "\n"
